#!/usr/bin/python3
import sys

# Here i am simply reading the ratings_genre.dat file which i generated by combining 
# the movie.dat with rating.dat from other python program. Then i am outputting values from
# that file which is being used in our reducer to find highest average rated movie genre.
for roww in sys.stdin:
    roww = roww.strip()
    u, m, r, _, Genres = roww.split("|")
    m = int(m)
    for jj in Genres.split(":"):
        print(f'{jj}\t{r}')